### ISSUE TITLE
Question about red line laser!

### ISSUE THREAD

**Issue by a312514554** [bq/ciclop#11]
What is the type of the Red line laser(5V) is in your Ciclop-BOM.pdf? Could you give me more information about it?Thanks!

**Comment by Jesus89** [comment]
Hi, our laser is a Class 1 5V red line laser with 60º of aperture "bq-made". You can use also another line lasers. There are some people in the community using it.

For future questions or discussions about Horus, please use our Google Group: https://groups.google.com/forum/?hl=en#!forum/ciclop-3d-scanner instead of a GitHub issue.

Regards!
